# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SubjectsExample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SubjectsExample
  pod 'RxSwift'                    , '~> 5'
  pod 'RxCocoa'                    , '~> 5'

  target 'SubjectsExampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SubjectsExampleUITests' do
    # Pods for testing
  end

end
