-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgflcobl7Dgl/LJJ5q
bZOiNPqdubGXYZY0040zcXiYDCugCgYIKoZIzj0DAQehRANCAATNJfioYD4eDZPk
Slvzz8/EBFWok/5uujECNUcnuUiFBsjK2IZC56Ks8FMd69RdN6FroDrlYjGptlj6
AAbwXVGU
-----END PRIVATE KEY-----